baseURL = "https://dtianyou.github.io/"
languageCode = "en-us"
title = "Cai's Blog"
theme = "cactus"
copyright = "Cai" # cactus will use title if copyright is not set
# disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"
# canonifyURLs = true


# summaryLength = 2

# Main menu which appears below site header.
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.zh]
    languageName = "中文"
    weight = 1
    title = "我的博客"
    contentDir = "content/zh"
    languageCode = "zh-cn"
    [languages.zh.params]
      description = "中文描述..."

  [languages.en]
    languageName = "English"
    weight = 2
    title = "My Blog"
    contentDir = "content/en"
    languageCode = "en"
    [languages.en.params]
      description = "This is Cai's blog. You can see the monthly and yearly posts here."

  # 分别设置中英文导航菜单
  [languages.zh.menu]
    [[languages.zh.menu.main]]

    name = "首页"
    url = "/zh/"
    weight = 1
    [[languages.zh.menu.main]]
    name = "文章"
    url = "/zh/posts/"
    weight = 2
    [[languages.zh.menu.main]]
    name = "项目"
    url = "/zh/projects/"
    weight = 3
    [[languages.zh.menu.main]]
    name = "关于"
    url = "/zh/about/"
    weight = 4

  [languages.en.menu]
    [[languages.en.menu.main]]
    name = "Home"
    url = "/en/"
    weight = 1
    [[languages.en.menu.main]]
    name = "Posts"
    url = "/en/posts/"
    weight = 2
    [[languages.en.menu.main]]
    name = "Projects"
    url = "/en/projects/"
    weight = 3
    [[languages.en.menu.main]]
    name = "About"
    url = "/en/about/"
    weight = 4



[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default

  # Home page settings
  # description = "This is Cai's blog. You can see the monthly and yearly posts here."

  mainSection = "posts" # your main section
  showAllPostsOnHomePage = true # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = false # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/gohugoio" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = true # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/patrlean"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/tianyou-zhao-7a972a2a4/"
  [[params.social]]
    name = "email"
    link = "tianyou.2001[at]outlook.com"  # no need for "mailto:" in the head

